# Generated by Django 5.1.6 on 2025-02-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vladenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adress", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("vladelec", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
